#!/usr/bin/env bash

#ddev-generated
## Description: Run Drupal core's commit-code-check script on your changes
## Usage: commit-code-check [flags]
## Example: "ddev commit-code-check --cached" for staged files or "ddev commit-code-check" for all working directory changes

exec "${DDEV_DOCROOT:+$DDEV_DOCROOT/}core/scripts/dev/commit-code-check.sh" "$@"
