#!/usr/bin/env bash

#ddev-generated
# Tab completion for 'ddev remove-module': the modules cloned with add-module.

. "$(dirname "$0")/../../../drupal-dev/completion-helpers.sh"

read_completion_words "$@"

if [ ${#POSITIONAL[@]} -eq 0 ]; then
  list_modules
fi
